---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    # Get the latest from:
    # https://github.com/antonbabenko/pre-commit-terraform/releases
    rev: v1.60.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: checkov
        args: [
          "--skip-path", "./dmz-proxy-helm"
        ]
      # - id: terraform_docs
